const FETCH_REQUEST = 'game/FETCH_REQUEST';
const FETCH_ERROR = 'game/FETCH_ERROR';
const FETCH_SUCCESS = 'game/FETCH_SUCCESS';
const GET_GAME_CONFIG = 'game/GET_GAME_CONFIG';
const SET_GAME_CONFIG = 'game/SET_GAME_CONFIG';
const GET_WINNERS = 'game/GET_WINNERS';
const UPDATE_WINNERS = 'game/UPDATE_WINNERS';
const SET_GAME_STATUS = 'game/SET_GAME_STATUS';
const GET_GAME_STATUS = 'game/GET_GAME_STATUS';
const GET_AVAILABLE_SETTINGS = 'game/GET_AVAILABLE_SETTINGS';
const SET_AVAILABLE_SETTINGS = 'game/SET_AVAILABLE_SETTINGS';

export default {
  FETCH_REQUEST,
  FETCH_ERROR,
  FETCH_SUCCESS,
  GET_GAME_CONFIG,
  SET_GAME_CONFIG,
  GET_WINNERS,
  UPDATE_WINNERS,
  SET_GAME_STATUS,
  GET_GAME_STATUS,
  GET_AVAILABLE_SETTINGS,
  SET_AVAILABLE_SETTINGS,
};
